# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2023.05.30-h06a4308_0.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-cudart-11.7.99-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-cupti-11.7.101-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvrtc-11.7.99-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvtx-11.7.91-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.38-h1181459_1.conda
https://conda.anaconda.org/nvidia/linux-64/libcublas-11.10.3.66-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufft-10.7.2.124-h4fbf590_0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufile-1.7.0.149-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcurand-10.3.3.53-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusolver-11.4.0.1-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusparse-11.7.4.91-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libnpp-11.7.4.75-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libnvjpeg-11.8.0.2-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2023c-h04d1e81_0.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-libraries-11.7.1-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-runtime-11.7.1-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-cuda-11.7-h778d358_5.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/giflib-5.2.1-h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmp-6.2.1-h295c915_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9e-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/lame-3.100-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lerc-3.0-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libdeflate-1.17-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libiconv-1.16-h7f8727e_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtasn1-4.19.0-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libunistring-0.9.10-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.41.5-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-base-1.2.4-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openh264-2.1.1-h4ff587b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-3.0.9-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.4.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2023.1.0-hdb19cb5_46305.conda
https://repo.anaconda.com/pkgs/main/linux-64/libidn2-2.3.4-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.39-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpfr-4.0.2-hb69a4c5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/nettle-3.7.3-hbbd107a_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.12-h1ccaba5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.5.5-hc292b87_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.12.1-h4a9f257_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gnutls-3.6.15-he1e5248_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.5.0-h6a678d5_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2023.1.0-h6d00ec8_46342.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpc-1.1.0-h10f8cd9_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.41.2-h5eee18b_0.conda
https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-1.2.4-h11a3e52_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.11.4-h955ad1f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2023.7.22-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/filelock-3.9.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmpy2-2.1.2-py311hc9b5ff0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/idna-3.4-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-2.1.1-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py311h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpmath-1.2.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/networkx-2.8.4-py311h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-9.4.0-py311h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-68.0.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.7.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.38.4-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.15.1-py311h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-3.1.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.25.0-py311hf175353_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-23.2.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sympy-1.11.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotlipy-0.7.0-py311h5eee18b_1002.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-41.0.2-py311h22a60cf_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-23.2.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.26.16-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.31.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.6-py311ha02d727_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.2-py311ha02d727_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.25.0-py311h08b1b3b_0.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-2.0.1-py3.11_cuda11.7_cudnn8.5.0_0.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchaudio-2.0.2-py311_cu117.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchtriton-2.0.0-py311.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchvision-0.15.2-py311_cu117.tar.bz2
